Fix for joint parameter constraints for ringdown PE
gwastro/pycbc pull request #3469
Opened 2020-09-24 13:23 UTC by a-r-williamson

When trying to place constraints on a `JointDistribution` while using `ringdown` models, an error occured due to the passing of the `lmns` argument (a list of strings) to initiation of a field array. Since this is a fixed parameter, this (and all other fixed params) don't need to be passed here. The fix is to only pass the variable params.

2020-09-24 13:27 UTC, ahnitz approved these changes

2020-09-24 13:31 UTC, cdcapano approved these changes

2020-09-24 16:03 UTC, a-r-williamson commented
The Travis build shows that this actually breaks `pycbc_create_injections` as seen in [`examples/inference/bbh-injection/make_injection.sh`](https://github.com/gwastro/pycbc/examples/inference/bbh-injection/make_injection.sh), since there are no variable params there.

2020-10-09 12:42 UTC, cdcapano requested changes
@a-r-williamson Could you rebase? I think the PR that @ahnitz recently pushed (#3433) might help with this, and is also the source of the merge conflict. 

Anyway, you're getting that error because in the injection example, all the parameters are static. Since there are no variable args, `params` is an empty dictionary, and you can't create a `FieldArray` for that. The fix is in `__call__`, check if the `params` is empty before calling `_ensure_fieldarray`. If it is, just return `True` at that point. Also, in the `__init__` check that `variable_args` isn't empty if constraints were provided. If constraints were provided, and `variable_args` is empty, raise an error.

2020-11-30 15:52 UTC, ahnitz commented
@a-r-williamson Poke. Can this be rebased?

2022-03-01 11:16 UTC, ahnitz commented
@cdcapano @a-r-williamson What's the status of this?

2022-03-01 11:16 UTC, ahnitz commented
@cdcapano can you verify that this should merge as is if the unittests pass?

2022-03-01 11:17 UTC, ahnitz commented
@a-r-williamson Can rebase and make sure the unittests pass?

2023-07-07 19:57 UTC, spxiwh commented
Closing due to being inactive for over 2 years. @cdcapano @ahnitz if this is still needed please rebase the branch into your fork and create a new PR (preserving authorship of the patches).

2023-07-07 19:57 UTC, closed without merging