Ringdown bugs
gwastro/pycbc pull request #3490
Opened 2020-10-06 13:15 UTC by JulianWesterweck

This corrects the order of arguments for the frequency domain ringdown waveform and ensures that the functions for the desired approximant are used.

2020-10-07 13:42 UTC, cdcapano requested changes
Thanks for fixing this Julian. Just a few requests related to how the `fd_approximant` and `td_approximant` are specified; see below.

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +            fd_approximant = True
Get rid of this if block when you change to a single `domain` argument; then just evaluate the `domain` below, raising an error if it isn't either `fd` or `td`. That means that you won't be trying to guess what to use based on the input params, but I think that's for the best. Having it try to guess can lead to unexpected results.

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +    if freq_tau_approximant or 'final_mass' not in input_params.keys():
Just base it on the `freq_tau_approximant`.

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
>      domains with parameters set by input_params.
Add a `Parameters` section to the doc string to explain what each keyword argument does. Also, you could combine this into a single, required argument `domain` that must be set to either `fd` or `td`. That'll simplify the logic below, and make it more straightforward to explain how to use the function.

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +    if td_approximant:
Change to `if domain == 'td':`

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +    elif fd_approximant:
`elif domain == 'fd':`

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
>                              input_params['delta_f'], input_params['f_final'])
Add here an
```
else:
    raise ValueError('unrecognized domain argument {}; '
                               'must be either fd or td'.format(domain))
```

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +    return multimode_base(input_params, td_approximant=True)
With the above changes, here replace `td_approximant=True` with `'td'`.

2020-10-07 13:42 UTC, cdcapano commented on pycbc/waveform/ringdown.py
> +    return multimode_base(input_params, fd_approximant=True)
And here `fd_approximant=True` -> `'fd'`. Ditto for the other places below.

2020-10-07 18:24 UTC, micamu reviewed
I am not quite sure if these comments I had written yesterday got to you, so clicking an extra button now in case they didn't. They seem to be in agreement with some of Collin's comments

2020-10-07 18:28 UTC, micamu commented
And I just saw the recent changes, I approve now :)

2020-10-07 18:29 UTC, micamu approved these changes

2020-10-07 18:31 UTC, JulianWesterweck commented
Indeed, I did not see your comments until now - thanks!
I will look at fixing the codeclimate complaint.

2020-10-09 13:30 UTC, cdcapano approved these changes

2020-10-09 13:30 UTC, cdcapano commented
Looks good, thank @JulianWesterweck

2020-10-09 13:31 UTC, merged