Fix potential errors in stat module, add basic test
gwastro/pycbc pull request #3586
Opened 2021-01-20 13:56 UTC by titodalcanton

@MPillas and I noticed that one of the simple coinc ranking stats are not usable with the multi-ifo workflow. When we tried using the `phasetd_newsnr_sgveto` stat, we get this error from some of the coinc jobs:
```
 Traceback (most recent call last):
  File "somewhere/pycbc-v1.16.13/bin/pycbc_multiifo_coinc_findtrigs", line 321, in 
    time_addition=args.coinc_threshold)
  File "somewhere/pycbc-v1.16.13/lib/python2.7/site-packages/pycbc/events/stat.py", line 151, in coinc_multiifo
    return sum(sngl[1] ** 2. for sngl in s) ** 0.5
  File "somewhere/pycbc-v1.16.13/lib/python2.7/site-packages/pycbc/events/stat.py", line 151, in 
    return sum(sngl[1] ** 2. for sngl in s) ** 0.5
TypeError: ufunc 'square' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I *think* I spotted where this is coming from, so this PR proposes a fix.

In addition, given that we should start working on #3584 soon, I added a basic unit test file for the stat module to hopefully make that easier. It is currently failing due to the various unimplemented stats, and the need for some stats to have their files passed to them, so I keep it disabled for now. It may be expanded and enabled as part of this PR though, depending on how the discussion goes.

2021-01-20 14:16 UTC, titodalcanton commented
Hmm ok, apparently PyCBC Live does not like the "fix". Putting on hold until someone has a chance to comment.

2021-01-21 11:27 UTC, titodalcanton commented
Looks like PyCBC Live needed just a trivial fix - removing the on-hold label.

2021-01-21 12:32 UTC, titodalcanton commented
Also tagging @GarethDaviesGW and @tdent.

2021-01-21 14:09 UTC, spxiwh requested changes
I don't think this is the right fix to the problem (see comments in line). This will definitely break the QuadratureSum statistic.

A possible solution is to enforce a common format for the output of `single` method, but we did try that initially, and it didn't work so we had to change it. Maybe the dictionary format is better though, and could be enforced for all statistics. (I emphasize though that this behaviour is unchanged from before ...)

2021-01-21 14:09 UTC, spxiwh commented on pycbc/events/stat.py
> -        cstat = sum(sngl[1] ** 2. for sngl in sngls_list) ** 0.5
I think this change is going to break this statistic in the standard workflow, where this statistic did work before and did not have a ['snglstat'] element.

Here, I've not changed the previous behaviour (although one might argue a change might be needed), where you call through to the `single` method of the Stat class to get whatever that returns (which can be computed without knowing anything about the other ifo(s), and then feeding that through to `rank_coinc`. For the QuadratureSum method you have not changed the `single` method, but have changed  the `rank_coinc` method, this breaks this statistic.

If possible, PyCBC Live should be doing the same and not manually constructing the single_info as you do on line 1046 of coinc.py but instead using the `single` method of `self.stat_calculator` and then passing that along .... Maybe there's some reason why it needs to do this though??

2021-01-21 14:12 UTC, spxiwh commented
@titodalcanton I read the code changes and didn't really read the comments. Indeed the `single` method (before and after refactoring) did return inconsistent output. But as this would only be used *within* each stat class, it was not a problem. The user should not have had to care as you should just let the stat class choose.

I think the prime problem here is that PyCBC Live is trying to guess this format itself. It shouldn't be doing any form of stat calculations (although I'm probably missing a reason why it needs to).

That said, I think the output from `single` perhaps could be unified. But I think what's here now will break the QuadratureSum class.

2021-01-22 13:36 UTC, closed without merging