set fake strain options, sample rate, filter settings, etc
gwastro/pycbc pull request #3588
Opened 2021-01-21 12:28 UTC by ahnitz

2021-01-21 12:31 UTC, ahnitz commented
This adds 3 options to the strain generation 

```
 --fake-strain-flow FAKE_STRAIN_FLOW
                        Low frequency cutoff of the fake strain
  --fake-strain-filter-duration FAKE_STRAIN_FILTER_DURATION
                        Duration in seconds of the fake data coloring filter
  --fake-strain-sample-rate FAKE_STRAIN_SAMPLE_RATE
                        Sample rate of the fake data generation
```

There are defaults for these similar to the current ones.

2021-01-21 12:36 UTC, ahnitz commented
@titodalcanton @spxiwh This also removes the strangely hidden dependence on an 'low-frequency-cutoff' option and makes it explicit for generating fake data. It also has a default which will be sufficient for current LIGO data.

2021-01-21 12:40 UTC, ahnitz commented
Note: All fake data will now be different after this patch.

2021-01-21 14:24 UTC, spxiwh requested changes
So I'm going to request an addition to the test suite alongside this. Can we add a test where we generate a small number of Gaussian noise sets (testing the various options that this module has) and check it's the same as a set of values stored in a HDF file (also added with this patch). 

I also note that if you had the block size as the old value of 1638400 you would produce the old output, although it's a weird number!

2021-01-21 14:24 UTC, spxiwh commented on pycbc/noise/reproduceable.py
> -# The hope is that nobody needs a higher resolution
Well, that hope didn't last ;-)

2021-01-21 15:50 UTC, ahnitz commented
> So I'm going to request an addition to the test suite alongside this. Can we add a test where we generate a small number of Gaussian noise sets (testing the various options that this module has) and check it's the same as a set of values stored in a HDF file (also added with this patch).
> 
> I also note that if you had the block size as the old value of 1638400 you would produce the old output, although it's a weird number!

This is a fair request. I'll think about it. I'm not sure I want us to be committing any more 'files' in the repo, but one might be able to do a checksum or similar for this kind of test. In addition, I think checking that the psd of the data matches the input psd might be a sensible sanity check.

2021-01-21 16:25 UTC, spxiwh commented
> > So I'm going to request an addition to the test suite alongside this. Can we add a test where we generate a small number of Gaussian noise sets (testing the various options that this module has) and check it's the same as a set of values stored in a HDF file (also added with this patch).
> > I also note that if you had the block size as the old value of 1638400 you would produce the old output, although it's a weird number!
> 
> This is a fair request. I'll think about it. I'm not sure I want us to be committing any more 'files' in the repo, but one might be able to do a checksum or similar for this kind of test. In addition, I think checking that the psd of the data matches the input psd might be a sensible sanity check.

I like the checksum idea, but we need to be careful that we expect byte-equal output. If for e.g. any FFT is involved in producing the PSD or the data, we'd need to ensure it is reproducible (use FFTW always with measurelvl=0 *should* do it)

2021-01-22 12:02 UTC, ahnitz commented
@spxiwh Ok, please look at this again. I've added a simple unit test at the moment that does mostly what we discussed. It's not really a checksum but likely close enough for what we want.

2021-01-25 12:59 UTC, spxiwh approved these changes

2021-01-25 13:14 UTC, merged