added Left and Right Circular Projection matrix
gwastro/pycbc pull request #3599
Opened 2021-01-27 10:05 UTC by JAMSADIQ

Added a new function in this code for left and right circular polarization projection matrix.

2021-01-27 13:36 UTC, spxiwh commented
@a-r-williamson I've assigned this one to you to look over.

2021-11-10 09:11 UTC, JAMSADIQ commented
With the above commits now pycbc-multi-inspiral and lalapps_coh_PTF_inspiral  code give same results when using left anf right circular polarization matrices. The details can be found at https://wiki.ligo.org/Bursts/CircularlyPolarizedProjectionMatrix
In order to check the code for accepting merge request my modified code can be used for an injection test with command line options given in https://wiki.ligo.org/Bursts/CircularlyPolarizedProjectionMatrix page.

2021-11-15 14:53 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +parser.add_argument("--projection-type", default='standard', type=str, help="""Choice of projection matrix with standard, left circular or right circular""")
```suggestion
parser.add_argument("--projection-type", default="standard",
                    choices=["standard", "left", "right", "left+right"],
                    help="Choice of projection matrix. 'Left' and 'right' "
                         "correspond to face-away and face-on.")
```

2021-11-15 14:53 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +def circular_projection_matrix(wp, wc):
Can we perhaps unify this into the above function `get_projection_matrix` which could have a kwarg for the projection name?

2021-11-15 14:53 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +            ####### Testing values
```suggestion
```

2021-11-15 14:53 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +            LCprojection_matrix, RCprojection_matrix = circular_projection_matrix(wp, wc)
We also need to account for the normal GRB search behaviour where both right and left projections are used.

2021-11-16 11:59 UTC, JAMSADIQ commented
I make changes and push them. Kindly check it

2021-11-16 14:37 UTC, titodalcanton commented on bin/pycbc_multi_inspiral
> +        logging.info("choice of projection matrix is not available")
This should probably be an exception, not a `logging.info()` call:
```python
raise ValueError('unknown projection type ' + str(projection_type))
```

2021-11-16 14:39 UTC, titodalcanton commented on bin/pycbc_multi_inspiral
> +                            % str(projection_type))
Calls to `logging.info()` should not use the string formatting operations (`%` and `.format()`). Instead, do this:
```python
logging.info("choice of projection matrix is %s", projection_type)
```
(this comment also applies to `logging.info()` further below).

2021-11-16 16:56 UTC, JAMSADIQ commented
Fixed some issues for review.

2022-02-02 16:40 UTC, a-r-williamson requested changes
Hi @JAMSADIQ, thanks for the recent commits. I've requested a few minor changes here, which hopefully you can just click accept on then I can approve the PR.

2022-02-02 16:40 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +            projection_type: standard, left or right
The kwarg here is `projection` not `projection_type`. Can you change the doc string?

2022-02-02 16:40 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
> +                logging.info("reweghtsnr, networkchi2 ={0}, {1}".format(num_events ,len(network_chisq_dict)))
```suggestion
```
Not a particularly useful logging message for it to remain IMO

2022-02-02 16:40 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
>                              % str(len(rho_coh)))
```suggestion
                logging.info("%d points above coherent threshold", len(rho_coh))
```

2022-02-02 16:40 UTC, a-r-williamson commented on bin/pycbc_multi_inspiral
>                                  % str(max(rho_coinc)))
```suggestion
                    logging.info("Max coincident SNR = %.2f", max(rho_coinc))
```

2022-02-02 17:26 UTC, merged