Add lowpass filter option to strain generation
gwastro/pycbc pull request #3806
Opened 2021-09-22 22:39 UTC by dethodav

This PR adds the option to lowpass strain data as part of `strain.from_cli`. The lowpass method is based on the lal lowpass function, and mirrors the method used for high passing as part of the current strain generation process. 

This PR was originally part of #3804, but is now a separate PR based on the suggestion of @titodalcanton.

2021-09-22 22:41 UTC, ahnitz approved these changes

2021-09-23 11:09 UTC, titodalcanton commented
@dethodav you probably should add the `--strain-low-pass` option to the function `insert_strain_option_group_multi_ifo()` as well. See how the twin option `--strain-high-pass` is mirrored there.

2021-09-23 11:14 UTC, titodalcanton requested changes

2021-09-23 11:14 UTC, titodalcanton commented on pycbc/filter/resample.py
> +        A  new TimeSeries that has been high-passed.
Low-passed.

2021-09-23 11:14 UTC, titodalcanton commented on pycbc/filter/resample.py
> +        The frequency below which is suppressed.
above which?

2021-09-23 11:14 UTC, titodalcanton commented on pycbc/filter/resample.py
> +
This empty line can be removed.

2021-09-23 11:14 UTC, titodalcanton commented on pycbc/filter/resample.py
> +__all__ = ['resample_to_delta_t', 'highpass', 'lowpass', 'interpolate_complex_frequency', 'highpass_fir', 'lowpass_fir', 'notch_fir', 'fir_zero_filter']
It seems Code Climate was complaining about this line being too long. Make sure it does not go beyond 79 characters.

2021-09-28 06:57 UTC, titodalcanton approved these changes

2021-09-28 07:31 UTC, merged