remove explicit subworkflow dependency
gwastro/pycbc pull request #3855
Opened 2021-11-02 18:44 UTC by ahnitz

This is one area I noticed as odd when I looked at the Pegasus 5 changes.

 Given that our internal method of setting sub-workflow inter-dependencies had been removed, I'm skeptical that this line here should be required. In other words, if we could remove the inter-workflow dependencies and pycbc's older code for determining dependencies base don file useage, then Pegasus must be determining this internally now.  The inputs for the workflow are already being added to the dax object directly. If that's the case, and it is doing so correctly, then this dependency line should not be required. 
 
Assuming the tests don't reveal something and I haven't misunderstood some corner case, I suggest we remove this line to remove future confusion about how dependencies are resolved.

2021-11-04 14:24 UTC, spxiwh requested changes
I think that it doesn't make sense to remove this line and *not* remove the parents key-word argument. There are some places (e.g. minifollowups) giving this parents=[node] argument, which it seems don't need to. 

.... So I do agree that this seems redundant, and I think we don't have an example case that needs to use this (or should be using this, even though some still are). However, it might be useful to keep this (perhaps wrapped in a "only do this if parents is not None" block) in the case that we want to add an explicit, non-file based, dependancy to a subworkflow. (While it's not quite the same, the finalization subworkflow is a case where an explicit dependency is used)

2021-11-17 21:08 UTC, spxiwh commented
Poke

2021-11-28 09:37 UTC, ahnitz commented
@spxiwh I'd like for us to decide on #3868 first to make sure the unittests added there are run.

2021-12-13 12:07 UTC, spxiwh commented
@ahnitz I guess this now needs rebasing after #3868 is merged. I think we're testing everything we should be now??

2021-12-22 16:26 UTC, ahnitz commented
@spxiwh Ok, I think this is now correct.

2022-01-06 13:55 UTC, spxiwh approved these changes

2022-01-06 13:55 UTC, merged