Verifier with pycbc injs
gwastro/pycbc pull request #4013
Opened 2022-05-02 19:42 UTC by pannarale

This PR allows `pycbc_make_bank_verifier_workflow` to also exploit `pycbc_create_injections` rather than just `lalapps_insp_inj`.  Doing so required some cleaning up in `pycbc/workflow/jobsetup.py`, which in turn also brought a small update to `pycbc_make_inference_inj_workflow`.  Finally, `pycbc/inject/inject.py` needed some fixing to get `pycbc_create_injections` to write aligned spin injections to xml files without errors.

2022-05-02 19:45 UTC, pannarale commented
@spxiwh, I assigned this to you, as the author of `pycbc_make_bank_verifier_workflow`.  @cdcapano, I brought you in the loop as this PR touches some injections material and as I had pinged you on chat regarding `pycbc_create_injections`.

2022-05-04 12:51 UTC, spxiwh requested changes
Thanks @pannarale there's a few minor requests here, but I think the only place that's non trivial is in how the `--config-file` option is handled in CreateInjections.

First up, I think this should be declared as a "file input option" so that pegasus will know what it is without the stuff here.

There's an example of setting it (and catching many examples of this) here:

https://github.com/gwastro/pycbc/blob/master/pycbc/workflow/core.py#L77

I'm happy if `--config-file` is added here as well, it's clear that that would always be a file!

With that dealt with, I think the only other thing you're doing here is copying the config file into the web directory. That does need some custom code to do it, so if you want that, you may end up with something close to what you have. *Or* you are happy just to have the main config file, which would point to the location of these files, on the cluster.

2022-05-04 12:51 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +request_disk = workflow.cp.get('pegasus_profile', 'condor|request_disk')
You shouldn't need this line, as it should be added automatically anyway,

2022-05-04 12:51 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +    if 'LalappsInspinjExecutable' in str(inspinj_exe):
I think you want `isinstance(inspinj_exe, LalappsInspinjExecutable)` for this

2022-05-04 12:51 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +        inj_conf_file_url = workflow.cp.get(subsection_name, 'config-file')
Don't do it like this. Add `--config-file` to the list of "file arguments" in PycbcCreateInjectionsExecutable, and then this all happens automatically!

2022-05-04 12:51 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +        inj_conf_file_url = workflow.cp.get(subsection_name, 'config-file')
This would mean that you don't get to say "leave this file in this directory", but I think that's okay to reduce complexity here.

2022-05-04 12:51 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +        inj_conf_file_url = workflow.cp.get(subsection_name, 'config-file')
... ALthough I think what you are doing here is adding the injection config files into the output directory, which then might be needed. But we *do* need to set `--config-file` in the list of file arguments for `PycbcCreateInjectionsExecutable` for this to be used in other workflows as well. In that case the config-file argument would always be a local path at this point, but you could still copy it around in this way.

2022-05-04 12:51 UTC, spxiwh commented on pycbc/inject/inject.py
> +        setattr(inj, sim_field, [0, 0, data])
Is this for XML inputs only? THere is a good chance that XML support will removed from this module *very* soon.

2022-05-04 12:51 UTC, spxiwh commented on pycbc/workflow/jobsetup.py
> +            extension = '.xml.gz'
Wouldn't that need to be `self.extension =` ?

2022-05-04 12:51 UTC, spxiwh commented on pycbc/workflow/jobsetup.py
> +        super(PycbcDarkVsBrightInjectionsExecutable, self).__init__(
No python2 support needed now, so I think this can just be `super().__init__`

2022-05-04 12:51 UTC, spxiwh commented on pycbc/workflow/jobsetup.py
> +    extension = '.hdf'
file_output option would go here.

2022-05-04 12:51 UTC, spxiwh commented on pycbc/workflow/jobsetup.py
>          super(PycbcCreateInjectionsExecutable, self).__init__(
Lots of places where we need to simplify `super()`

2022-05-06 16:25 UTC, pannarale commented
Thanks, @spxiwh!  I think the easiest thing to do is to use the already existing infrastructure for `--config-files`, without adding `--config-file`.  The one character difference could cause other unwanted problems when writing configuration files that would be hard to spot; additionally, this leaves the door open for a user wanting to pass multiple configuration files to the `pycbc_create_injections`  jobs here.

Having said that, the code changes are simpler!  And with one line I managed to preserve all inifies in `results/` which I really think we should have for reproducibility, and so new users can pick all of this up more easily.

The one (I think!) thing I have not been able to improve is the `isinstance` issue you brought up.  Let me know what you think about that.  There may be something obvious to do that I have not thought of.

2022-05-09 08:32 UTC, spxiwh approved these changes
Thanks @pannarale , I'll give approval now, but I would prefer that the `isinstance` thing is updated before merging (but leave that up to you).

The other thing to highlight here, which I won't delay this PR with, is that XML support in anything other than `convert_XML_to_hdf` is expected to be removed soon. I think that the HDF bank splitter should also work as a HDF injection splitter, but it would be good to expect `bank_verifier` to work with HDF files, using the `convert_XML_to_HDF` job to initially convert if XML input files are given (as opposed to generating files with inspinj/create_injections. create_injections is not expected to support XML output for much longer.

2022-05-09 08:32 UTC, spxiwh commented on bin/workflows/pycbc_make_bank_verifier_workflow
> +    if 'LalappsInspinjExecutable' in str(inspinj_exe):
I would say that this is the only remaining comment I would push back on. You are testing if the instance `inspinj_exe` is a certain class or not. `isinstance` is a builtin function for doing exactly this, casting to `str` and testing that feels messy.

2022-05-12 07:30 UTC, merged