Fix lalsuite links
gwastro/pycbc pull request #4101
Opened 2022-08-08 15:45 UTC by spxiwh

This fixes #3974 by updating links to lalsuite in the install lalsuite documentation page to that recommended by @duncanmmacleod.

2022-08-08 22:36 UTC, tdent commented on docs/install_lalsuite.rst
> +`instructions on the DASWG pages for cloning lalsuite <https://wiki.ligo.org/Computing/LALSuiteInstall>`_.
There are no 'DASWG pages' any more.  They are LSC Computing/Software pages

2022-08-08 22:37 UTC, tdent requested changes
OK modulo 'DASWG' -> CompSoft or similar

2022-08-09 08:52 UTC, spxiwh commented
Thanks Tom! DASWG has been changed to LSC Computing as requested.

2022-08-09 08:57 UTC, tdent approved these changes

2022-08-09 09:42 UTC, merged