add two heterodyne / relative likelihood models dedicated to sky marginalization
gwastro/pycbc pull request #4203
Opened 2022-12-04 13:12 UTC by ahnitz

This adds two new models of the heterodyne type. One is focused on 22-mode only optimizations, while the other is left more generic. An example is added for the latter (which inherits from the former). 

Depends on #4202

2022-12-08 12:55 UTC, spxiwh commented
@ahnitz I think this depends on some ohter patches that are open, so I'll try to review this promptly once the dependencies are all in! (Although others may be better reviewers than me on this!)

2023-01-19 12:27 UTC, ahnitz commented
@cdcapano @spxiwh I think this should be ready to look at now.

2023-01-30 15:48 UTC, ahnitz commented
@spxiwh @cdcapano Poke?

2023-01-31 12:01 UTC, spxiwh reviewed
This looks good to me, but others know this code better than me.

I think it would be good to add more explanation of what the new models do, and what the options in the `model` section of the ini file actually mean. Maybe it would be good to add details into the documentation to describe this??

2023-01-31 15:54 UTC, ahnitz commented
@spxiwh All the options were part of previous PRs and not completely specific to these models. I agree having some more documentation on what the different models are / can do would be good. I've been thinking about putting together a table or something like that for the docs, might as well do that now, but in a separate PR.

2023-02-06 20:44 UTC, cdcapano requested changes
Hard to check the math, but if you ran the tests in the examples and they look ok, it seems fine. Needs more documentation though (see comment). Also, I noticed you're running cprofile in the example script. Is that on purpose, or was that an accidental copy? If on purpose, add a comment explaining that so people don't think it's necessary to do that in order to run pycbc inference.

2023-02-06 20:44 UTC, cdcapano commented on pycbc/inference/models/relbin.py
> +    """
This needs some more documentation. What's the difference between this and `RelativeTime`? Also not crazy about the name... if `Domain` meant by `Dom`, just call it `RelativeTimeDomain`.

2023-02-06 20:46 UTC, cdcapano commented
@ahnitz The more extensive docs you suggest in your reply to Ian sounds good, but I would still request at least a brief synopsis in the class doc string for `RelativeTime` and `RelativeTimeDom` for people looking at source code and/or using the help in Jupyter. Right now they're identical, which is confusing.

2023-03-21 09:42 UTC, ahnitz commented
@spxiwh @cdcapano Sorry, it took me a while to get back to this. I've updated the docstrings to clarify the difference between them i.e. the RelativeTimeDom only works for Dominant-mode only waveforms.

2023-03-21 15:59 UTC, cdcapano approved these changes
Looks good.

2023-03-21 16:00 UTC, merged