Use a fixed verson of BBHx
gwastro/pycbc pull request #4304
Opened 2023-04-01 17:58 UTC by WuShichao

@ahnitz This PR uses a fixed version number for BBHx, so any changes in its main branch will not affect PyCBC build tests. I contacted Katz, and he released a new release (v1.0.5) for PyCBC.

2023-04-01 18:30 UTC, ahnitz requested changes
Don't fix an exact version. If we need to specify a minimum that is Ok, but we absolutely do want to catch if upstream needs to be fixed or vice-versa.

2023-04-01 18:36 UTC, ahnitz commented
@WuShichao @spxiwh It hink it might be worth now to think about contributing some things back upstream. Maybe the plugin itself in addition to some unittests and maybe a cibuildwheel config so we don't have to rebuild BBHx most of the time. Thoughts?

2023-04-01 18:39 UTC, WuShichao commented
@ahnitz Good suggestions! Katz is on vacation until May, so we have enough time to think about this.

2023-04-02 20:33 UTC, ahnitz commented
@WuShichao Does this syntax actually get the required version, or does it just checkout master in all cases?

2023-04-03 13:59 UTC, WuShichao commented
@ahnitz I have searched how to specify a minimum release number for pip install from GitHub (not just from master branch, but from a formal release) https://stackoverflow.com/questions/68315468/pip-install-latest-release-from-github. It seems not very elegant.

2023-04-03 14:05 UTC, ahnitz commented
@WuShichao Think we should maybe abandon this then and instead just help BBHx to start doing formal releases with wheels. That way we can use regular pip commands.

2023-04-03 14:11 UTC, WuShichao commented
@ahnitz That's correct, `wheels` can do that. Let me close this PR, and think about how to contribute to BBHx itself.

2023-04-03 14:11 UTC, closed without merging