Allow pycbc_multi_inspiral to search over a sky grid
gwastro/pycbc pull request #4380
Opened 2023-05-30 10:40 UTC by hoangstephanie

At the moment, `pycbc_multi_inspiral` can only search over a single sky position. However, it needs to search over a sky grid covering the GRB error box.

This pull request implements this change. `pycbc_multi_inspiral` now takes an hdf file containing two datasets, `latitude` and `longitude`. The command-line arguments `--ra` and `--dec` are thus removed. After matched-filtering is done, it loops over the sky positions and time slides to perform the coincident and coherent search.

It also fixes the output values of `latitude` and `longitude` which were not correctly written before (set to 0 for all triggers).

This plot below shows, when clustering is disabled, that we indeed get the same triggers when running `pycbc_multi_inspiral` only once over 2 sky points and running `pycbc_multi_inspiral` twice over a single sky position each time : 

![image](https://github.com/gwastro/pycbc/assets/105010876/5d39ce3c-7a01-4c9d-b114-03e0bc113407)

The CPU time for the search over a sky grid has also been checked : 
![image](https://github.com/gwastro/pycbc/assets/105010876/5132aca0-81fc-451e-9b73-99440d59c4c1)

2023-06-01 12:20 UTC, titodalcanton commented
@hoangstephanie as we discussed, the tests are failing because the example still requires the `--ra` and `--dec` options. I propose you keep the ability to use either `--ra` and `--dec` *or* `--sky-grid`. If they are given at the same time, an error should be printed using `parser.error()`.

2023-06-02 08:16 UTC, hoangstephanie commented
The tests are still failing because I have renamed the command lines `--ra` and `--dec` to `--latitude` and `--longitude` to match the datasets contained in the sky grid and the names of the ouputs. I am thinking of doing a pull request for the example to change the name of the parameters given.

2023-06-02 08:50 UTC, titodalcanton commented
@hoangstephanie rather than opening a new PR, you should change the example in *this* PR, so that the example continues to match the code.

2023-06-22 11:57 UTC, pannarale requested changes

2023-06-22 11:57 UTC, pannarale commented on bin/pycbc_multi_inspiral
> +    antenna_patterns = [[[0 for i in range(2)] for position_index in positions_array] for i in range(3)]
The 3 should not be hardcoded.

2023-06-29 11:17 UTC, pannarale approved these changes

2023-06-29 11:20 UTC, merged