Try to fix CI tests
gwastro/pycbc pull request #4394
Opened 2023-06-09 20:53 UTC by spxiwh

I'll write a proper description if this actually works ....

2023-06-10 18:42 UTC, ahnitz commented
@spxiwh Can we add an error message to let the user know what to do if they do try to use a > 2**24 point FFT with MKL? I think it might be worth it in this case.

2023-06-10 20:35 UTC, spxiwh commented
@ahnitz Yes, it would be good to add this.

Can we do this separately from this PR though? This PR doesn't change any behaviour in MKL and I'd prefer to limit this to "let's just get the CI suite working again" and then consider MKL and how to handle longer arrays separately (I'm hoping there is an easy way to get MKL to work on longer arrays. The "descriptor" object seems to be the place to look, but the documentation is ... not great.)

2023-06-11 16:48 UTC, ahnitz approved these changes

2023-06-11 20:14 UTC, josh-willis commented
So for some reason when I install from this branch and run a basic threading test I had setup, setting the threading backend to `openmp` isn't actually changing the threading backend (e.g., using ` --fftw-threads-backend openmp` in a program using our builtin CLI functions). This could be some problem with my test as I don't see how the changes on this branch could have led to that, but I want to understand what's going on first...

2023-06-11 21:05 UTC, josh-willis commented
> So for some reason when I install from this branch and run a basic threading test I had setup, setting the threading backend to `openmp` isn't actually changing the threading backend (e.g., using ` --fftw-threads-backend openmp` in a program using our builtin CLI functions). This could be some problem with my test as I don't see how the changes on this branch could have led to that, but I want to understand what's going on first...

Indeed, the problem was with my test, which specified `--fftw-threads-backend openmp` but not `--fft-backend`. With this patch of course I must do so to exercise FFTW as the backend.

For me, this patch also seems to resolve the segfault error in a conda environment which has  all of MKL, BLAS linked to MKL, and liblal linked to FFTW. Not sure why it would do that, but that's great, since it's much simpler than what I had been working on.  I will add a review with a couple of minor requests but this has my in-principle approval.

2023-06-11 21:10 UTC, josh-willis requested changes
I've requested changes but since Alex has approved, once the changes are made (at least the one about updating the comment line please) consider this approved from me and go ahead and merge, so CI is back to working.

2023-06-11 21:10 UTC, josh-willis commented on pycbc/fft/fftw.py
> +            if double_threaded_libname.endswith('omp'):
Can this test instead be:
```
if backend == 'openmp':
```
since I think it's clearer?

2023-06-11 21:10 UTC, josh-willis commented on pycbc/fft/fftw.py
> +        _backend_list = ['unthreaded','openmp', 'pthreads']
Please also change the comment line immediately above to indicate that now 'pthreads' is the first thing tried, or we'll get very confused later.

2023-06-11 21:15 UTC, josh-willis approved these changes

2023-06-11 21:16 UTC, josh-willis commented
I would still like the changes but am removing "Changes requested" so that this does not have to wait on me approving said changes...

2023-06-12 10:38 UTC, spxiwh commented
Thanks Josh. The changes suggested make sense. I'll implement this and then get this merged.

2023-06-12 12:27 UTC, merged