Update pycbc_brute_bank to include option to cut wavelength and save …
gwastro/pycbc pull request #4506
Opened 2023-09-27 14:41 UTC by kkacanja

…the lower frequency

2023-09-27 16:09 UTC, kkacanja commented on bin/bank/pycbc_brute_bank
> +            logging.info("failed at 2")
Remove this line

2023-09-28 15:18 UTC, ahnitz requested changes

2023-09-28 15:18 UTC, ahnitz commented on bin/bank/pycbc_brute_bank
> +                import numpy
Shouldn't need to reimport numpy

2023-09-28 15:18 UTC, ahnitz commented on bin/bank/pycbc_brute_bank
> +                import numpy
Move the determination of the waveform length and corresponding flow to top of this function so the result can be used by the remainder with less code duplication.

2023-09-28 15:18 UTC, ahnitz commented on bin/bank/pycbc_brute_bank
> +                kwds['flow'] = f
Should be named 'f_lower'

2023-09-29 17:56 UTC, ahnitz commented on bin/bank/pycbc_brute_bank
> +                    help="When enabled, the program will adjust the wavelength to fit the specified length in max-signal-length ")
We could probably combine these two options, so if max-signal-length isn't given, it doesn't impose any cut.

2023-09-29 19:04 UTC, ahnitz commented
@kkacanja Let me know when you want me to review this.

2023-10-23 16:01 UTC, ahnitz commented on bin/bank/pycbc_brute_bank
> +        flow = numpy.arange(self.f_lower, 100, .1)[::-1]
This line and the next should probably be within the if statement.

2023-10-23 16:02 UTC, ahnitz approved these changes
@kkacanja Besides for the minor comment which should be straightforward to address, I think this is ready to merge.

2023-10-24 16:20 UTC, kkacanja commented
> @kkacanja In general, you should use a "rebase" rather than merging master into your code.

Thank you, I am unfamiliar with rebasing so I will do that now.

2023-10-25 19:43 UTC, ahnitz commented
@kkacanja Some of the tests are fragile to network outages. So for example, if data can't be retrieved when it tries. You have to take a look at the message to see if it looks like this is the case when you see a failure (or if the error seems related to your PR). If it's the former, there should be a button you can click to restart any failed jobs and have them try again. If not, we can walk through this together tomorrow and make sure you have the right permissions set up.

2023-10-25 19:44 UTC, merged