Sorting_plotting_kde
gwastro/pycbc pull request #4544
Opened 2023-10-26 13:37 UTC by PRAVEEN-mnl

2023-10-26 13:56 UTC, tdent commented
I guess there are 3 possible ways to deal with the sorting: first, you leave the values in the order they are in the file; second, you sort in ascending order (highest on top); third, you sort in descending order (lowest on top).  Also I think 'normal' doesn't really explain what the option means. 

So I would suggest having three possible options, ie 'file', 'increasing', 'decreasing', with the default being 'file'

2023-10-26 16:33 UTC, tdent commented on bin/all_sky_search/pycbc_plot_kde_vals
> +param_arrays = [param[idx] for param in param_arrays]
Maybe put a comment before this line, eg `Sort each of the parameter arrays`

2023-10-27 13:30 UTC, PRAVEEN-mnl commented
I did `git fetch origin` and `git rebase origin/master` on my master branch before creating a new branch. 

This branch was created just to introduce the sorting but the code became repetitive.
For example:  `--plot-type` has 2 choices: kde_vs_param & param_vs_param. In both, ax.scatter() line gets repeated 6 times overall in the code. The new code uses it twice.
Also, during sorting, the parameters need to be called again.
The new code produces the same plots as before. I have tried plotting all the combinations of params along with  `--which-kde`

2023-10-27 13:31 UTC, PRAVEEN-mnl commented
> I don't understand why there are 6 commits here and why there are more changes in the plotting code than just introducing the sorting. When you want to make a new change, update your local copy of the main (/master) branch to get changes from the remote repo then make a new feature branch for the pull request.

2023-10-27 15:39 UTC, tdent commented
OK, I thought there had been a git problem because these extra changes were not explained by the title or the description of the PR so I did not know why they were there.  That is why you should have a description in the PR unless the changes are really simple and self-explanatory, so that the reviewer knows why the changes are being made.

2023-10-27 15:45 UTC, tdent commented on bin/all_sky_search/pycbc_plot_kde_vals
> +kde_values = kde_arrays[args.which_kde]
As you don't use the variable `kde_arrays` anywhere else, can you just do this instead? 
```
kde_values = {
    'signal_kde': signal_kde,
    'template_kde': template_kde,
    'ratio_kde': signal_kde / template_kde,
}[args.which_kde]
```

2023-10-27 15:47 UTC, tdent requested changes
Minor change to use of dictionary, otherwise looks OK

2023-10-30 12:54 UTC, tdent approved these changes

2023-10-30 20:33 UTC, merged