Update rates-based statistics to be modular
gwastro/pycbc pull request #4608
Opened 2024-01-24 12:04 UTC by GarethCabournDavies

## Overview of changes

The exponential fit statistics are all similar, with simple factors added or subtracted, as discussed in #4594

I have refactored the `ExpFitStatistic` to be able to use the different features using a `--statistic-features` option. These then all use `exp_fit` as the `--ranking-statistic` option

The available features are:
| Feature | Description | Notes |
| --- | --- | --- |
| `phasetd` | Apply a factor of how the phase, time and amplitude differences match up to what is expected for signals. | |
| `kde` | Apply a factor according to a kernel density estimate of the ratio of signal and noise distributions for each template. | |
| `dq` | Apply a factor according to any data quality channel information. | |
| `chirp_mass` | Apply a reweighting according to the chirp mass of the template. | |
| `sensitive_volume` | Apply a factor of the log of sensitive volume (compared to a median for the template). This means that the statistic takes into account any changes in the detector sensitivity and that, e.g., we expect to see more events in the HL network than HV coincidences. | |
| `normalize_fit_rate` | Normalize the rates fits by the analysis time. This is needed so that the statistic is comparable over chunks of different lengths. | This was done for all `exp_fit` statistics, but is implemented here explicitly so that the `exp_fit_csnr` statistic can reuse the `lognoiserate` function from the `ExpFitStatistic` |

I have also removed the different treatment of triggers with sngl_ranking below threshold; this is now required explicitly as `--statistic-keywords alpha_below_threshold:6`. Again this was so that the `exp_fit_csnr` statistic can reuse the `lognoiserate` function from the `ExpFitStatistic`

In addition, there are some minor changes as well to fix some of the statistics which didn't work at all on previous master. There is a (just for reference) PR at #4607 to show these.

## Testing

I have tested all existing (and working) statistics to check that given the appropriate features, the output remains identical.

The testing is done against the codes in #4607, so that we can test statistics against what they _should_ be, rather than what they are.

Initial tests with a very small fraction of the bank have shown that the SNR-like statistics output files have identical hashes. The exp_fit statistics outputs are all the same to within a numpy.isclose test, i.e. ~1e-6 difference for values O(1). But I will add the results of more stringent testing here.

| Statistic | New statistic | Features | Keywords | pycbc_sngls_findtrigs output | pycbc_coinc_findtrigs output |
| --- | --- | --- | --- | --- | --- |
| quadsum | quadsum | | |  |  |
| single_ranking_only | single_ranking_only | -- | -- |  |  |
| phasetd | phasetd | -- | -- |  |  |
| exp_fit_csnr | exp_fit_csnr | -- | -- |  |  |
| phasetd_exp_fit_fgbg_norm | exp_fit | `phasetd sensitive_volume normalize_fit_rate` |  `alpha_below_thresh:6` | | |
| phasetd_exp_fit_fgbg_bbh_norm | exp_fit | `phasetd sensitive_volume normalize_fit_rate chirp_mass` | `alpha_below_thresh:6` | | |
| phasetd_exp_fit_fgbg_kde | exp_fit | `phasetd sensitive_volume normalize_fit_rate kde` | `alpha_below_thresh:6` | | |
| dq_phasetd_exp_fit_fgbg_norm | exp_fit | `phasetd sensitive_volume normalize_fit_rate dq` | `alpha_below_thresh:6` | | |
| dq_phasetd_exp_fit_fgbg_kde | exp_fit | `phasetd sensitive_volume normalize_fit_rate dq kde` | `alpha_below_thresh:6` | | |

2024-01-25 11:54 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +            raise NotImplementedError(err_msg)
This shouldn't actually happen due to the argparse choices, but safety is best

2024-01-25 11:54 UTC, GarethCabournDavies commented on bin/all_sky_search/pycbc_sngls_findtrigs
> +    trigger_times = trigs['end_time'][:][trigger_keep_ids]
Some singles objects don't have the end time included

2024-01-25 11:54 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +_allowed_statistic_features = [
I'm not sure where is best to describe each feature here to be honest

2024-01-25 11:54 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +class ExpFitStatistic(PhaseTDStatistic):
Subclassing PhaseTDStatistic here in order to get the phasetd stuff in __init__

2024-02-06 09:16 UTC, GarethCabournDavies commented
The numbers in the comparison table have been updated

I am sure it is not a coincidence that the error in the coincs is double that of the singles, but I think a ~4e-6 difference is not too important given the dynamic range of the statistic.

2024-02-06 10:33 UTC, GarethCabournDavies commented
I am adding a description of the statistics to the docs - I am writing it in the `pycbc_make_offline_search_workflow` documentation at the moment, but that can be moved if requested.

2024-02-06 14:48 UTC, GarethCabournDavies commented
Note that I found and fixed a bug in the way that  `sngl_ranking_` keywords are handled and passed through to the ranking module

2024-05-21 17:23 UTC, maxtrevor commented
Noting here that it was suggested on today's call that we want to wait to merge this until after creating the new PyCBC Live branch intended for the rest of O4

2024-12-13 14:31 UTC, GarethCabournDavies commented
I think this is ready for review now. All tests are passing

I haven't been able to test how this works with Live as well as I would like to; there seems to be a problem with my testing environment

2025-01-07 11:16 UTC, GarethCabournDavies commented
Poke @spxiwh post-winter break

2025-01-09 14:07 UTC, spxiwh requested changes
Some comments below, but nothing significant. It's hard to review the bulk of changes here because of the amount of code being moved around, but the sanity checks look convincing. @ahnitz do you any concerns/comments?

2025-01-09 14:29 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +            trigs, self.sngl_ranking, **self.sngl_ranking_kwargs
Reverted

2025-01-09 14:29 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +        self.ref_snr = 5.0
Changed back

2025-01-09 14:30 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +        Calculate the normalized log rate density of coincident signals
The line was too long when adding "coincident" - I've changed to "coinc" and it is okay now

2025-01-09 15:00 UTC, GarethCabournDavies commented on docs/workflow/pycbc_make_offline_search_workflow.rst
> +
I've put it into a separate page within a "search" section of the docs page - the rest of this would obviously need building up more to be particularly useful!

2025-01-13 11:57 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +class ExpFitStatistic(PhaseTDStatistic):
This is a good point - I've added an `type(self).__name__ == "PhaseTD" or self.kwargs["phasetd"]` check so that this is only called during in `init()` if needed

2025-01-13 12:04 UTC, GarethCabournDavies commented on pycbc/events/stat.py
> +class ExpFitStatistic(PhaseTDStatistic):
though right now, `pregenerate` hist doesn't have any way to be set, so `get_hist()` is only called when the `coinc_lim_for_thresh` / `rank_stat_coinc` are called for the first time. so it doesn't have any code paths to try and get the histograms when files aren't set unless they are actually needed.

2025-01-20 12:23 UTC, spxiwh approved these changes
I think I'm happy with this now. Please do poke Alex to see if he has any thoughts before merging.

2025-01-22 10:38 UTC, merged