Exclusion distance correction
gwastro/pycbc pull request #4904
Opened 2024-10-09 18:32 UTC by ETVincent

There was a bug for the PyGRB analysis wherein the 50% exclusion distance was not reported accurately in the table. You can see an example of the issue here: [https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_2/6._open_box/6.02_exclusion_distances/](https://ldas-jobs.ligo.caltech.edu/~francesco.pannarale/LVC/pygrb_sep2024_2/6._open_box/6.02_exclusion_distances/) wherein the reported 50% exclusion distance does not match that from the plot. 

## Standard information about the request

This is a bug fix to correct the issue. 

This change affects: PyGRB.

## Contents
It appears as though there was some extra duplicated code. This extra code was removed. 

Additionally, a variable was converted from an int into a dictionary to hold the information better. 

## Testing performed
During testing, the reported 50% exclusion distance was closer to that from the plot. 
<img src="https://github.com/user-attachments/assets/acd1ac96-8340-4ac5-8bac-6824e71322fd" width="500">

<img src="https://github.com/user-attachments/assets/4e4423a3-57ac-4d88-a1d6-68a9e2625f77" width="500">

- [ ] The author of this pull request confirms they will adhere to the [code of conduct](https://github.com/gwastro/pycbc/blob/master/CODE_OF_CONDUCT.md)

2024-10-10 13:19 UTC, pannarale requested changes

2024-10-10 13:19 UTC, pannarale commented on bin/pygrb/pycbc_pygrb_efficiency
> +excl_dist = {}
It looks like you can use this dictionary only, and remove `excl_dist_dict`.  Details below.

2024-10-10 13:19 UTC, pannarale commented on bin/pygrb/pycbc_pygrb_efficiency
> +        excl_dist[percentile] = d + (e - (percentile / 100.)) * (d - d_low) /\
```suggestion
        excl_dist[f"{percentile}%"] = d + (e - (percentile / 100.)) * (d - d_low) /\
```

2024-10-10 13:19 UTC, pannarale commented on bin/pygrb/pycbc_pygrb_efficiency
> +        excl_dist[percentile] = 0
```suggestion
        excl_dist[f"{percentile}%"] = 0
```

2024-10-10 13:19 UTC, pannarale commented on bin/pygrb/pycbc_pygrb_efficiency
> +    excl_dist_dict['90%'] = excl_dist[90]
```suggestion
    excl_dist['inj_set'] = inj_set_name
    excl_dist['trial_name'] = opts.trial_name
```

2024-10-10 13:19 UTC, pannarale commented on bin/pygrb/pycbc_pygrb_efficiency
> +    plot_caption += f" 50%% sensitive distance: {excl_dist[50]} Mpc"
```suggestion
    plot_caption += f" 90%% exclusion distance: {excl_dist['90%']} Mpc\n"
    plot_caption += f" 50%% sensitive distance: {excl_dist['50%']} Mpc"
```

2024-10-21 18:01 UTC, ETVincent commented on bin/pygrb/pycbc_pygrb_efficiency
> +    excl_dist_dict['90%'] = excl_dist[90]
Completed in update below

2024-10-22 07:15 UTC, pannarale approved these changes

2024-10-22 07:16 UTC, merged